version: 2.1
# orbs - reusable packages
orbs:
  node: circleci/node@5.0.1
  docker: circleci/docker@2.1.4
  snyk: snyk/snyk@1.5.0
# jobs - set of instructions / functions
jobs:
  scan:
    docker:
      - image: cimg/node:16.10
    environment:
      IMAGE_NAME: kelvin3118/education-space
    steps:
      - checkout
      - setup_remote_docker
      - docker/check
      - run: docker build -t $IMAGE_NAME .
      - snyk/scan:
          docker-image-name: $IMAGE_NAME
  build: # job name
    docker: # environment
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: |
          echo "Installing dependencies..."
          npm install
  test:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: |
          echo "Running tests..."
          npm run test
  publish: #also known as build-and-push
    executor: docker/docker #define the execution environment in which the steps of a job will run
    steps:
      - checkout
      - setup_remote_docker
      - docker/check
      - docker/build: #build the image
          image: kelvin3118/education-space
          tag: v1.0.1
      - docker/push: #pushes the image to the specified account in the environment
          image: kelvin3118/education-space
          tag: v1.0.1

# workflow - defines what sequence the jobs will run
workflows:
  simple_workflow: # workflow name
    jobs:
      - build:
          filters:
            branches:
              only: main
      - test:
          requires: # added build job requirement for test jobs
            - build
          filters:
            branches:
              only: main
      - scan: # scan job
          requires:
            - build
          filters:
            branches:
              only: main
          steps:
            - snyk/scan:
                severity-threshold: high
